CREATE TABLE "import_runs" (
	"id" serial PRIMARY KEY NOT NULL,
	"filename" text NOT NULL,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"finished_at" timestamp with time zone,
	"rows_total" integer DEFAULT 0 NOT NULL,
	"rows_inserted" integer DEFAULT 0 NOT NULL,
	"rows_updated" integer DEFAULT 0 NOT NULL,
	"rows_error" integer DEFAULT 0 NOT NULL,
	"status" text DEFAULT 'running' NOT NULL,
	"error_message" text
);
--> statement-breakpoint
CREATE TABLE "source_products" (
	"id" serial PRIMARY KEY NOT NULL,
	"modell_erweitert" text NOT NULL,
	"modell" text,
	"lieferanten_artikel_nr" text,
	"ean_code" text,
	"kurz_bezeichnung_de" text,
	"lang_bezeichnung_de" text,
	"kurz_bezeichnung_en" text,
	"lang_bezeichnung_en" text,
	"hauptkategorie" text,
	"kategorie_ebene1" text,
	"kategorie_ebene2" text,
	"kategorie_ebene3" text,
	"hauptmaterial" text,
	"legierung" text,
	"legierungsgewicht" double precision,
	"caratur" double precision,
	"anzahl_steine" integer,
	"diamant_schliffguete" text,
	"diamant_farbe" text,
	"diamant_reinheit" text,
	"caratur_farbstein" double precision,
	"anzahl_steine_farbstein" integer,
	"einkaufspreis" double precision,
	"einkaufspreis_waehrung" text,
	"uvp" double precision,
	"uvp_waehrung" text,
	"bestand" integer,
	"ringgroesse" text,
	"hoehe" double precision,
	"breite" double precision,
	"durchmesser" double precision,
	"staerke" double precision,
	"produkt_laenge_cm" double precision,
	"freisteller_url" text,
	"modelbild_url" text,
	"bild_urls" jsonb,
	"beschaffenheit" text,
	"gia_zertifikat_nr" text,
	"liefertermin" text,
	"angelegt" text,
	"geaendert" text,
	"aehnliche_artikel" text,
	"raw_json" jsonb,
	"status" text DEFAULT 'neu' NOT NULL,
	"shopify_product_id" text,
	"sent_to_pipeline_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "source_products_modell_erweitert_unique" UNIQUE("modell_erweitert")
);
--> statement-breakpoint
CREATE INDEX "status_idx" ON "source_products" USING btree ("status");--> statement-breakpoint
CREATE INDEX "kategorie_ebene1_idx" ON "source_products" USING btree ("kategorie_ebene1");--> statement-breakpoint
CREATE INDEX "hauptmaterial_idx" ON "source_products" USING btree ("hauptmaterial");--> statement-breakpoint
CREATE INDEX "bestand_idx" ON "source_products" USING btree ("bestand");